// Code generated by Kitex v0.12.3. DO NOT EDIT.

package refundservice

import (
	api "DouTok-example/backend/baseService/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RefundCreate(ctx context.Context, Req *api.RefundCreateRequest, callOptions ...callopt.Option) (r *api.RefundCreateResponse, err error)
	RefundQuery(ctx context.Context, Req *api.RefundQueryRequest, callOptions ...callopt.Option) (r *api.RefundQueryResponse, err error)
	RefundUpdate(ctx context.Context, Req *api.RefundUpdateRequest, callOptions ...callopt.Option) (r *api.RefundUpdateResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRefundServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRefundServiceClient struct {
	*kClient
}

func (p *kRefundServiceClient) RefundCreate(ctx context.Context, Req *api.RefundCreateRequest, callOptions ...callopt.Option) (r *api.RefundCreateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundCreate(ctx, Req)
}

func (p *kRefundServiceClient) RefundQuery(ctx context.Context, Req *api.RefundQueryRequest, callOptions ...callopt.Option) (r *api.RefundQueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundQuery(ctx, Req)
}

func (p *kRefundServiceClient) RefundUpdate(ctx context.Context, Req *api.RefundUpdateRequest, callOptions ...callopt.Option) (r *api.RefundUpdateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundUpdate(ctx, Req)
}
