// Code generated by Kitex v0.12.3. DO NOT EDIT.

package payservice

import (
	api "DouTok-example/backend/baseService/kitex_gen/api"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Pay": kitex.NewMethodInfo(
		payHandler,
		newPayArgs,
		newPayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	payServiceServiceInfo                = NewServiceInfo()
	payServiceServiceInfoForClient       = NewServiceInfoForClient()
	payServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return payServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return payServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return payServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PayService"
	handlerType := (*api.PayService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func payHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.PayRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.PayService).Pay(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PayArgs:
		success, err := handler.(api.PayService).Pay(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PayResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPayArgs() interface{} {
	return &PayArgs{}
}

func newPayResult() interface{} {
	return &PayResult{}
}

type PayArgs struct {
	Req *api.PayRequest
}

func (p *PayArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.PayRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PayArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PayArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PayArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PayArgs) Unmarshal(in []byte) error {
	msg := new(api.PayRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PayArgs_Req_DEFAULT *api.PayRequest

func (p *PayArgs) GetReq() *api.PayRequest {
	if !p.IsSetReq() {
		return PayArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PayArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PayResult struct {
	Success *api.PayResponse
}

var PayResult_Success_DEFAULT *api.PayResponse

func (p *PayResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.PayResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PayResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PayResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PayResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PayResult) Unmarshal(in []byte) error {
	msg := new(api.PayResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PayResult) GetSuccess() *api.PayResponse {
	if !p.IsSetSuccess() {
		return PayResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PayResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.PayResponse)
}

func (p *PayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PayResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Pay(ctx context.Context, Req *api.PayRequest) (r *api.PayResponse, err error) {
	var _args PayArgs
	_args.Req = Req
	var _result PayResult
	if err = p.c.Call(ctx, "Pay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
