// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *CacheRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CacheRequest[number], err)
}

func (x *CacheRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Group, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CacheRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Key, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CacheResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CacheResponse[number], err)
}

func (x *CacheResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Value, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *CacheRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *CacheRequest) fastWriteField1(buf []byte) (offset int) {
	if x.Group == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetGroup())
	return offset
}

func (x *CacheRequest) fastWriteField2(buf []byte) (offset int) {
	if x.Key == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetKey())
	return offset
}

func (x *CacheResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *CacheResponse) fastWriteField1(buf []byte) (offset int) {
	if len(x.Value) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 1, x.GetValue())
	return offset
}

func (x *CacheRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *CacheRequest) sizeField1() (n int) {
	if x.Group == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetGroup())
	return n
}

func (x *CacheRequest) sizeField2() (n int) {
	if x.Key == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetKey())
	return n
}

func (x *CacheResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *CacheResponse) sizeField1() (n int) {
	if len(x.Value) == 0 {
		return n
	}
	n += fastpb.SizeBytes(1, x.GetValue())
	return n
}

var fieldIDToName_CacheRequest = map[int32]string{
	1: "Group",
	2: "Key",
}

var fieldIDToName_CacheResponse = map[int32]string{
	1: "Value",
}
