// Code generated by Kitex v0.12.3. DO NOT EDIT.

package authservice

import (
	api "DouTok-example/backend/baseService/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateVerificationCode(ctx context.Context, Req *api.CreateVerificationCodeRequest, callOptions ...callopt.Option) (r *api.CreateVerificationCodeResponse, err error)
	ValidateVerificationCode(ctx context.Context, Req *api.ValidateVerificationCodeRequest, callOptions ...callopt.Option) (r *api.ValidateVerificationCodeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) CreateVerificationCode(ctx context.Context, Req *api.CreateVerificationCodeRequest, callOptions ...callopt.Option) (r *api.CreateVerificationCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVerificationCode(ctx, Req)
}

func (p *kAuthServiceClient) ValidateVerificationCode(ctx context.Context, Req *api.ValidateVerificationCodeRequest, callOptions ...callopt.Option) (r *api.ValidateVerificationCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateVerificationCode(ctx, Req)
}
